name: Go package

on: [push]

jobs:
  test:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Tidy
        run: go mod tidy

      - name: Install mockgen
        run: go install github.com/golang/mock/mockgen@v1.6.0

      - name: Generate
        run: go generate -v ./...

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...